services:
  app:
    ports:
      - "8080:8080"  # Переопределение порта, чтобы приложение было доступно на 8080
    command: make dev  # Команда для запуска приложения в режиме разработки
    volumes:
      - ./app:/app  # Монтируем директорию app