on:
  push:

jobs:
  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Run tests
        env:
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        run: make ci
  deploy:
    name: Build and push a docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }} 
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.production
          push: true
          tags: sanichmyshkin/devops-for-programmers-project-74:latest
          platforms: linux/amd64