name: dockerhub-push

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }} 

      - name: Build docker image
        run: make build
  
      - name: Push docker image
        run: make push

      - name: Run tests
        run: make ci